"""Add User + RefreshToken + Note user_id

Revision ID: 98603198faed
Revises: b51d0dea291b
Create Date: 2025-11-30 15:43:31.718661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy import table, column, String, Integer
from app.pwdTest import TEST_HASHED_PWD


# revision identifiers, used by Alembic.
revision: str = '98603198faed'
down_revision: Union[str, Sequence[str], None] = 'b51d0dea291b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('refreshtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('note', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_note_user', 'note', 'user', ['user_id'], ['id'])

    conn = op.get_bind()
    user_table = table(
        'user',
        column('email', String),
        column('hashed_password', String)
    )
    # Insert default admin
    conn.execute(
        user_table.insert().values(
            email='MainAdmin@mail.com',
            hashed_password=TEST_HASHED_PWD
        )
    )
    # Get the inserted user ID
    result = conn.execute(
        sa.text('SELECT id FROM "user" WHERE email = :email'),
        {'email': 'MainAdmin@mail.com'}
    )
    default_user_id = result.scalar()

    # Backfill all notes
    conn.execute(
        sa.text("UPDATE note SET user_id = :uid"),
        {'uid': default_user_id}
    )
    # Make user_id NOT NULL after backfilling
    op.alter_column('note', 'user_id', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_note_user', 'note', type_='foreignkey')
    op.drop_column('note', 'user_id')
    op.drop_table('refreshtoken')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
