"""Making default user an admin

Revision ID: cd7cb690479c
Revises: 82223bcf8bb4
Create Date: 2025-12-08 21:25:53.093065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7cb690479c'
down_revision: Union[str, Sequence[str], None] = '82223bcf8bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    conn = op.get_bind()
    conn.execute(
        sa.text("UPDATE \"user\" SET is_admin = true WHERE email = :email"),
        {"email": "MainAdmin@mail.com"}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    conn = op.get_bind()
    conn.execute(
        sa.text("UPDATE \"user\" SET is_admin = false WHERE email = :email"),
        {"email": "MainAdmin@mail.com"}
    )
    # ### end Alembic commands ###
