from sqlmodel import SQLModel, Field, Relationship
from typing import Optional, List
from datetime import datetime, timezone
import sqlalchemy as sa

def now_utc():
    return datetime.now(timezone.utc)

class NoteBase(SQLModel):
    title: str = Field(max_length=50, sa_type=sa.String) # 1
    content: str = Field(max_length=500, sa_type=sa.String) # 1


class Note(NoteBase, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    created_at: datetime = Field(default_factory=now_utc) # 2
    user_id: int = Field(foreign_key="user.id")
    updated_at: Optional[datetime] = Field(
        default_factory=now_utc,
        sa_column_kwargs={"onupdate": now_utc} # 3
    )

class User(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True) # Auto-incrementing primary key
    email: str = Field(index=True, unique=True)
    hashed_password: str
    notes: List[Note] = Relationship(back_populates="owner") # Declares a one-to-many relationship

Note.owner = Relationship(back_populates="notes") # Declares a rlationship- a note has a single owner

class RefreshToken(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id")
    token: str
    expires_at: datetime = Field(default_factory=now_utc)

"""
Notes

1. sa_type=sa.String - defined to remove AutoString() from autogenerated alembic migration file
2. default_factory=now_utc - automatically sets default value of created_at = now_utc when new note is created
3. sa_column_kwargs={"onupdate": now_utc} - automatically sets updated_at = now_utc whenever the row is updated
"""